{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Hyperledger Besu JSON-RPC API",
    "description": "Hyperledger Besu JSON-RPC API enables interaction with a Besu Ethereum node\n\n## Notice\nThis is a public end-point! It is not encrypted. Encrypted RPC access involves registration!\n\nhttps://github.com/freight-trust",
    "contact": {},
    "termsOfService": "https://gist.githubusercontent.com/sambacha/078a91255acf3791cb5a77ba609b650c/raw/be4c3e847fe599b0124b85636bfd88958631cfc1/EXAMPLE_TOS_NOTICE.txt"
  },
  "host": "127.0.0.1:8545",
  "basePath": "/",
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/": {
      "post": {
        "summary": "web3_clientVersion",
        "tags": ["web"],
        "operationId": "web3_clientVersion",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/web3_clientVersion_Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "web3_clientVersion_Request": {
      "title": "web3_clientVersion_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "web3_clientVersion",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "net_peerCount_Request": {
      "title": "net_peerCount_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "net_peerCount",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_protocolVersion_Request": {
      "title": "eth_protocolVersion_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_protocolVersion",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_newPendingTransactionFilter_Request": {
      "title": "eth_newPendingTransactionFilter_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_newPendingTransactionFilter",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_uninstallFilter_Request": {
      "title": "eth_uninstallFilter_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_uninstallFilter",
        "params": ["0x70355a0b574b437eaa19fe95adfedc0a"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getFilterLogs_Request": {
      "title": "eth_getFilterLogs_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getFilterLogs",
        "params": ["0x5ace5de3985749b6a1b2b0d3f3e1fb69"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getLogs_Request": {
      "title": "eth_getLogs_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getLogs",
        "params": [
          {
            "fromBlock": "earliest",
            "toBlock": "latest",
            "address": "0x2e1f232a9439c3d459fceca0beef13acc8259dd8",
            "topics": []
          }
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "Param": {
      "title": "Param",
      "example": {
        "fromBlock": "earliest",
        "toBlock": "latest",
        "address": "0x2e1f232a9439c3d459fceca0beef13acc8259dd8",
        "topics": []
      },
      "type": "object",
      "properties": {
        "fromBlock": {
          "type": "string"
        },
        "toBlock": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "topics": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["fromBlock", "toBlock", "address", "topics"]
    },
    "eth_newBlockFilter_Request": {
      "title": "eth_newBlockFilter_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_newBlockFilter",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getFilterChanges_Request": {
      "title": "eth_getFilterChanges_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getFilterChanges",
        "params": ["0xf8bf5598d9e04fbe84523d42640b9b0e"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_newFilter_Request": {
      "title": "eth_newFilter_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_newFilter",
        "params": [
          {
            "fromBlock": "earliest",
            "toBlock": "latest",
            "topics": []
          }
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param1"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "Param1": {
      "title": "Param1",
      "example": {
        "fromBlock": "earliest",
        "toBlock": "latest",
        "topics": []
      },
      "type": "object",
      "properties": {
        "fromBlock": {
          "type": "string"
        },
        "toBlock": {
          "type": "string"
        },
        "topics": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["fromBlock", "toBlock", "topics"]
    },
    "eth_chainId_Request": {
      "title": "eth_chainId_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_chainId",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_gasPrice_Request": {
      "title": "eth_gasPrice_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_gasPrice",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_sendRawTransaction": {
      "title": "eth_sendRawTransaction",
      "example": {
        "jsonrpc": "2.0",
        "id": 1,
        "result": "0xac182cc23bb94696217aa17ca15bd466106af9ba7ea7420aae24ff37338d6e3b"
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "result": {
          "type": "string"
        }
      },
      "required": ["jsonrpc", "id", "result"]
    },
    "eth_blockNumber_Request": {
      "title": "eth_blockNumber_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_blockNumber",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getBalance_Request": {
      "title": "eth_getBalance_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getBalance",
        "params": ["0xfe3b557e8fb62b89f4916b721be55ceb828dbd73", "latest"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getProof_Request": {
      "title": "eth_getProof_Request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getStorageAt_Request": {
      "title": "eth_getStorageAt_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getStorageAt",
        "params": ["0x3B3F3E", "0x0", "latest"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getTransactionCount_Request": {
      "title": "eth_getTransactionCount_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getTransactionCount",
        "params": ["0x9d8f8572f345e1ae53db1dFA4a7fce49B467bD7f", "latest"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getBlockTransactionCountByHash_Request": {
      "title": "eth_getBlockTransactionCountByHash_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getBlockTransactionCountByHash",
        "params": [
          "0xb903239f8543d04b5dc1ba6579132b143087c68db1b2168786408fcbce568238"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getBlockTransactionCountByNumber_Request": {
      "title": "eth_getBlockTransactionCountByNumber_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getBlockTransactionCountByNumber",
        "params": ["0xe8"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getUncleCountByBlockHash_Request": {
      "title": "eth_getUncleCountByBlockHash_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getUncleCountByBlockHash",
        "params": [
          "0xb903239f8543d04b5dc1ba6579132b143087c68db1b2168786408fcbce568238"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getUncleByBlockHashAndIndex_Request": {
      "title": "eth_getUncleByBlockHashAndIndex_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getUncleByBlockHashAndIndex",
        "params": [
          "0xc48fb64230a82f65a08e7280bd8745e7fea87bc7c206309dee32209fe9a985f7",
          "0x0"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getUncleByBlockNumberAndIndex_Request": {
      "title": "eth_getUncleByBlockNumberAndIndex_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getUncleByBlockNumberAndIndex",
        "params": ["0x7689D2", "0x0"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getUncleCountByBlockNumber_Request": {
      "title": "eth_getUncleCountByBlockNumber_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getUncleCountByBlockNumber",
        "params": ["latest"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getCode_Request": {
      "title": "eth_getCode_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getCode",
        "params": ["0xa50a51c09a5c451c52bb714527e1974b686d8e77", "latest"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_sendRawTransaction_Request": {
      "title": "eth_sendRawTransaction_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_sendRawTransaction",
        "params": [
          "0xf86a018203e882520894f17f52151ebef6c7334fad080c5704d77216b732896c6b935b8bbd400000801ba093129415f03b4794fd1512e79ee7f097e4271f66721020f8407aac92179893a5a0451b875d89721ec98be55201092980b0a87bb1c48507fccb86da713596b2a09e"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getTransactionReceipt_Request": {
      "title": "eth_getTransactionReceipt_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getTransactionReceipt",
        "params": [
          "0x96c6830efd87a70020d4d1647c93402d747c05ecf6beeb068dee621f8d13d8d1"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_call_request": {
      "title": "eth_call_request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param2"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "Param2": {
      "title": "Param2",
      "example": {
        "to": "0x69498dd54bd25aa0c886cf1f8b8ae0856d55ff13",
        "value": "0x1"
      },
      "type": "object",
      "properties": {
        "to": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "eth_estimateGas_Request": {
      "title": "eth_estimateGas_Request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param3"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "Param3": {
      "title": "Param3",
      "example": {
        "from": "0x687422eea2cb73b5d3e242ba5456b782919afc85",
        "to": "0xdd37f65db31c107f773e82a4f85c693058fef7a9",
        "value": "0x1"
      },
      "type": "object",
      "properties": {
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "eth_getBlockByHash_Request": {
      "title": "eth_getBlockByHash_Request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getBlockByNumber_Request": {
      "title": "eth_getBlockByNumber_Request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getTransactionByHash_Request": {
      "title": "eth_getTransactionByHash_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getTransactionByHash",
        "params": [
          "0xa52be92809541220ee0aaaede6047d9a6c5d0cd96a517c854d944ee70a0ebb44"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getTransactionByHash": {
      "title": "eth_getTransactionByHash",
      "example": {
        "jsonrpc": "2.0",
        "id": 1,
        "result": null
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "result": {
          "type": "string"
        }
      },
      "required": ["jsonrpc", "id", "result"]
    },
    "eth_getTransactionByBlockHashAndIndex_Request": {
      "title": "eth_getTransactionByBlockHashAndIndex_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "params": [
          "0xa52be92809541220ee0aaaede6047d9a6c5d0cd96a517c854d944ee70a0ebb44",
          "0x1"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getTransactionByBlockNumberAndIndex_Request": {
      "title": "eth_getTransactionByBlockNumberAndIndex_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "params": ["latest", "0x0"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eth_getWork_Request": {
      "title": "eth_getWork_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eth_getWork",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "perm_getAccountsWhitelist_Request": {
      "title": "perm_getAccountsWhitelist_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "perm_getAccountsWhitelist",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "perm_addAccountsToWhitelist_Request": {
      "title": "perm_addAccountsToWhitelist_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "perm_addAccountsToWhitelist",
        "params": [
          [
            "0xb9b81ee349c3807e46bc71aa2632203c5b462032",
            "0xb9b81ee349c3807e46bc71aa2632203c5b462034"
          ]
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "perm_removeAccountsFromWhitelist_Request": {
      "title": "perm_removeAccountsFromWhitelist_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "perm_removeAccountsFromWhitelist",
        "params": [
          [
            "0xb9b81ee349c3807e46bc71aa2632203c5b462032",
            "0xb9b81ee349c3807e46bc71aa2632203c5b462034"
          ]
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "perm_getNodesWhitelist_Request": {
      "title": "perm_getNodesWhitelist_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "perm_getNodesWhitelist",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "perm_addNodesToWhitelist_Request": {
      "title": "perm_addNodesToWhitelist_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "perm_addNodesToWhitelist",
        "params": [
          [
            "enode://7e4ef30e9ec683f26ad76ffca5b5148fa7a6575f4cfad4eb0f52f9c3d8335f4a9b6f9e66fcc73ef95ed7a2a52784d4f372e7750ac8ae0b544309a5b391a23dd7@127.0.0.1:30303",
            "enode://2feb33b3c6c4a8f77d84a5ce44954e83e5f163e7a65f7f7a7fec499ceb0ddd76a46ef635408c513d64c076470eac86b7f2c8ae4fcd112cb28ce82c0d64ec2c94@127.0.0.1:30304"
          ]
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "perm_removeNodesFromWhitelist_Request": {
      "title": "perm_removeNodesFromWhitelist_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "perm_removeNodesFromWhitelist",
        "params": [
          [
            "enode://7e4ef30e9ec683f26ad76ffca5b5148fa7a6575f4cfad4eb0f52f9c3d8335f4a9b6f9e66fcc73ef95ed7a2a52784d4f372e7750ac8ae0b544309a5b391a23dd7@127.0.0.1:30303",
            "enode://2feb33b3c6c4a8f77d84a5ce44954e83e5f163e7a65f7f7a7fec499ceb0ddd76a46ef635408c513d64c076470eac86b7f2c8ae4fcd112cb28ce82c0d64ec2c94@127.0.0.1:30304"
          ]
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "perm_reloadPermissionsFromFile_Request": {
      "title": "perm_reloadPermissionsFromFile_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "perm_reloadPermissionsFromFile",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "clique_getSignerMetrics_Request": {
      "title": "clique_getSignerMetrics_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "clique_getSignerMetrics",
        "params": ["1", "100"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "clique_getSigners_Request": {
      "title": "clique_getSigners_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "clique_getSigners",
        "params": ["latest"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "clique_getSignersAtHash_Request": {
      "title": "clique_getSignersAtHash_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "clique_getSignersAtHash",
        "params": [
          "0x98b2ddb5106b03649d2d337d42154702796438b3c74fd25a5782940e84237a48"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "ibft_discardValidatorVote_Request": {
      "title": "ibft_discardValidatorVote_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "ibft_discardValidatorVote",
        "params": ["0x42eb768f2244c8811c63729a21a3569731535f06"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "ibft_proposeValidatorVote_Request": {
      "title": "ibft_proposeValidatorVote_Request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "ibft_getValidatorsByBlockNumber_Request": {
      "title": "ibft_getValidatorsByBlockNumber_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "ibft_getValidatorsByBlockNumber",
        "params": ["0x09"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "ibft_getValidatorsByBlockHash_Request": {
      "title": "ibft_getValidatorsByBlockHash_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "ibft_getValidatorsByBlockHash",
        "params": [
          "0x98b2ddb5106b03649d2d337d42154702796438b3c74fd25a5782940e84237a48"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "ibft_getPendingVotes_Request": {
      "title": "ibft_getPendingVotes_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "ibft_getPendingVotes",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "ibft_getSignerMetrics_Request": {
      "title": "ibft_getSignerMetrics_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "ibft_getSignerMetrics",
        "params": ["1", "100"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "debug_traceTransaction_Request": {
      "title": "debug_traceTransaction_Request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param4"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "Param4": {
      "title": "Param4",
      "type": "object",
      "properties": {
        "disableStorage": {
          "type": "boolean"
        }
      }
    },
    "debug_traceBlockByHash_Request": {
      "title": "debug_traceBlockByHash_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "debug_traceBlockByHash",
        "params": [
          "0xaceb3b2c9b25b0589230873921eb894b28722011b8df63977145517d754875a5"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "debug_traceBlock_Request": {
      "title": "debug_traceBlock_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "debug_traceBlock",
        "params": [
          "0xf90277f90208a05a41d0e66b4120775176c09fcf39e7c0520517a13d2b57b18d33d342df038bfca01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794e6a7a1d47ff21b6321162aea7c6cb457d5476bcaa00e0df2706b0a4fb8bd08c9246d472abbe850af446405d9eba1db41db18b4a169a04513310fcb9f6f616972a3b948dc5d547f280849a87ebb5af0191f98b87be598a0fe2bf2a941abf41d72637e5b91750332a30283efd40c424dc522b77e6f0ed8c4b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000860153886c1bbd82b44382520b8252088455c426598b657468706f6f6c2e6f7267a0b48c515a9dde8d346c3337ea520aa995a4738bb595495506125449c1149d6cf488ba4f8ecd18aab215f869f86780862d79883d2000825208945df9b87991262f6ba471f09758cde1c0fc1de734827a69801ca088ff6cf0fefd94db46111149ae4bfc179e9b94721fffd821d38d16464b3f71d0a045e0aff800961cfce805daef7016b9b675c137a6a41a548f7b60a3484c06a33ac0"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "debug_traceBlockByNumber_Request": {
      "title": "debug_traceBlockByNumber_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "debug_traceBlockByNumber",
        "params": [
          "0xaceb3b2c9b25b0589230873921eb894b28722011b8df63977145517d754875a5"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "debug_accountRange_Request": {
      "title": "debug_accountRange_Request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "debug_storageRangeAt_Request": {
      "title": "debug_storageRangeAt_Request",
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "admin_nodeInfo_Request": {
      "title": "admin_nodeInfo_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "admin_nodeInfo",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "admin_addPeer_Request": {
      "title": "admin_addPeer_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "admin_addPeer",
        "params": [
          "enode://c93f69ddd83d3db3e93e5165d60b4f5d93a9731df776beee94c5f8a0c770e41bdea69094136402db0cef7af63f0aa636ff676d4a88c6d37276dfa4160c21ed5f@127.0.0.1:30303"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "admin_removePeer_Request": {
      "title": "admin_removePeer_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "admin_removePeer",
        "params": [
          "enode://f59c0ab603377b6ec88b89d5bb41b98fc385030ab1e4b03752db6f7dab364559d92c757c13116ae6408d2d33f0138e7812eb8b696b2a22fe3332c4b5127b22a3@127.0.0.1:30304"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "admin_changeLogLevel_Request": {
      "title": "admin_changeLogLevel_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "admin_changeLogLevel",
        "params": ["DEBUG"],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "txpool_pantheonTransactions_Request": {
      "title": "txpool_pantheonTransactions_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "txpool_besuTransactions",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "txpool_pantheonStatistics_Request": {
      "title": "txpool_pantheonStatistics_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "txpool_besuStatistics",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "eea_sendRawTransaction_Request": {
      "title": "eea_sendRawTransaction_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "eea_sendRawTransaction",
        "params": [
          "0xf869018203e882520894f17f52151ebef6c7334fad080c5704d77216b732881bc16d674ec80000801ba02da1c48b670996dcb1f447ef9ef00b33033c48a4fe938f420bec3e56bfd24071a062e0aa78a81bf0290afbc3a9d8e9a068e6d74caa66c5e0fa8a46deaae96b0833"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "priv_distributeRawTransaction_Request": {
      "title": "priv_distributeRawTransaction_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "priv_distributeRawTransaction",
        "params": [
          "0xf869018203e882520894f17f52151ebef6c7334fad080c5704d77216b732881bc16d674ec80000801ba02da1c48b670996dcb1f447ef9ef00b33033c48a4fe938f420bec3e56bfd24071a062e0aa78a81bf0290afbc3a9d8e9a068e6d74caa66c5e0fa8a46deaae96b0833"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "priv_getPrivacyPrecompileAddress_Request": {
      "title": "priv_getPrivacyPrecompileAddress_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "priv_getPrivacyPrecompileAddress",
        "params": [],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "priv_getPrivateTransaction_Request": {
      "title": "priv_getPrivateTransaction_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "priv_getPrivateTransaction",
        "params": [
          "0x623c4ce5275a87b91f4f1c521012d39ca19311c787bde405490f4c0426a71498"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "priv_getTransactionReceipt_Request": {
      "title": "priv_getTransactionReceipt_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "priv_getTransactionReceipt",
        "params": [
          "0xf3ab9693ad92e277bf785e1772f29fb1864904bbbe87b0470455ddb082caab9d"
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "priv_createPrivacyGroup_Request": {
      "title": "priv_createPrivacyGroup_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "priv_createPrivacyGroup",
        "params": [
          {
            "addresses": [
              "sTZpbQhcOfd9ZaFDnC00e/N2Ofv9p4/ZTBbEeVtXJ3E=",
              "quhb1pQPGN1w8ZSZSyiIfncEAlVY/M/rauSyQ5wVMRE="
            ],
            "name": "Group A",
            "description": "Description Group A"
          }
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param5"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "Param5": {
      "title": "Param5",
      "example": {
        "addresses": [
          "sTZpbQhcOfd9ZaFDnC00e/N2Ofv9p4/ZTBbEeVtXJ3E=",
          "quhb1pQPGN1w8ZSZSyiIfncEAlVY/M/rauSyQ5wVMRE="
        ],
        "name": "Group A",
        "description": "Description Group A"
      },
      "type": "object",
      "properties": {
        "addresses": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": ["addresses", "name", "description"]
    },
    "priv_deletePrivacyGroup_Request": {
      "title": "priv_deletePrivacyGroup_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "priv_deletePrivacyGroup",
        "params": ["ewuTVoc5nlvWMwTFdRRK/wvV0dcyQo/Pauvx5bNEbTk="],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "priv_findPrivacyGroup_Request": {
      "title": "priv_findPrivacyGroup_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "priv_findPrivacyGroup",
        "params": [
          [
            "negmDcN2P4ODpqn/6WkJ02zT/0w0bjhGpkZ8UP6vARk=",
            "g59BmTeJIn7HIcnq8VQWgyh/pDbvbt2eyP0Ii60aDDw="
          ]
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    },
    "priv_getTransactionCount_Request": {
      "title": "priv_getTransactionCount_Request",
      "example": {
        "jsonrpc": "2.0",
        "method": "priv_getTransactionCount",
        "params": [
          "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",
          "kAbelwaVW7okoEn1+okO+AbA4Hhz/7DaCOWVQz9nx5M="
        ],
        "id": 1
      },
      "type": "object",
      "properties": {
        "jsonrpc": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": ["jsonrpc", "method", "params", "id"]
    }
  },
  "tags": [
    {
      "name": "web"
    },
    {
      "name": "net"
    },
    {
      "name": "eth"
    },
    {
      "name": "permissioning"
    },
    {
      "name": "clique"
    },
    {
      "name": "ibft"
    },
    {
      "name": "debug"
    },
    {
      "name": "miner"
    },
    {
      "name": "admin"
    },
    {
      "name": "rpc"
    },
    {
      "name": "txpool"
    },
    {
      "name": "eea"
    },
    {
      "name": "priv"
    }
  ]
}
